### ISSUE TITLE
Gdal error

### ISSUE THREAD

**Issue by yagmurn** [yumorishita/LiCSBAS#41] opened 2020-11-21 12:04 UTC
Dear Prof.,
[202011202042batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/5577578/202011202042batch_LiCSBAS_01_16.log)

I am trying to install gdal, I took an error as "failed with initial frozen solve. Retrying with flexible solve". I created new environment and installed gdal. But when I run the batch_LiCSBAS.sh file, I took error as "No module named gdal". 
Then I tried the second example using LiCSBAS.yml and run batch_LİCSBAS.sh file.  I took an error again. Log file is attached. 

Best

**Comment by lamebird** [comment] 2020-11-21 19:20
I think the problem is happened because you don't have gdal installed.
I've had this issue when installing gdal in full anaconda installation.
Have you tried creating new environment with miniconda and use "conda env create -f LiCSBAS.yml"?

**Comment by yagmurn** [comment] 2020-11-21 20:41
I tried that and gdal was installed. But I took error in the log file.

**Comment by yumorishita** [comment] 2020-11-21 23:21
You are using old version and the bug should be fixed in the latest module updated on 18 Nov. Please update your installed LiCSBAS and try again.

**Comment by yumorishita** [comment] 2020-11-30 06:04
It seems that the problem has been solved. I close this issue.

**Closed by yumorishita** 2020-11-30 06:04 UTC
