### ISSUE TITLE
How to run the script with new datas from other sites

### ISSUE THREAD

**Issue by duyhoangatk** [yumorishita/LiCSBAS#364] opened 2024-06-03 01:06 UTC
Hi Prof Yumorishita,
Sorry to ask you again. I'm practicing analyzing and have few questions about it.
1. Is there anyway to add other datas to the result folder without running script again from beginning because some places don't have the data's time that I want (Ex: I want to know the displacement of a place from 2020/01/01 until 2024/05/01 but the latest data is only until 2023/06/03, so I'm thinking that I will add the datas from 2023/07/01 from other sites to folder and run again) ? If there is, can you share which site can I download to match the data downloaded from COMET ?
2.  Can you share me the site where explains the meaning of every legend in the result graph (such as 'vel(1)', 'vel(2)', 'mask',... until 'hgt') ?

Maybe these are very basic questions but I'm still new so again sorry to ask.
Waiting for your reply. Thank you very much.

**Comment by yumorishita** [comment] 2024-06-03 12:48
1. I don't know any other sites. I generally recommend creating all the unwrapped data yourself if COMET data is not enough.
2. Please see Table 1 in the [LiCSBAS paper](https://www.mdpi.com/2072-4292/12/3/424).
vel(2): https://github.com/yumorishita/LiCSBAS/issues/117#issuecomment-878956383

![image](https://github.com/yumorishita/LiCSBAS/assets/37470321/7a6fbf9c-d6d9-40db-9dd9-cc41f0e156dc)

**Comment by duyhoangatk** [comment] 2024-06-04 07:42
Hi Prof Yumorishita,
Thank you for your kind response. Now I'm having this issue below when running batch script that after finishing download datas, the process is not running anymore just stop at downloading files (this error may occur depending on places)
![Batch script stop when finish download, not continue to run](https://github.com/yumorishita/LiCSBAS/assets/171003463/f0ef87e1-a4c0-46e7-a28d-6f109a047abb)
How can I fix this problem. 
Waiting for your reply. Thank you very much.

**Comment by duyhoangatk** [comment] 2024-06-05 00:00
Hi Prof Yumorishita,
I have retried to run batch script again, and it happens new error as following:
![New error](https://github.com/yumorishita/LiCSBAS/assets/171003463/bc54609a-7f5b-4575-8173-7977cb7d8739)
How can I fix this ? 
Waiting for your reply. Thank you very much.

**Comment by yumorishita** [comment] 2024-06-06 13:20
The bug was fixed in LiCSBAS2 (https://github.com/yumorishita/LiCSBAS2/pull/55). Please use LiCSBAS2 or apply the fix in your local LiCSBAS script.

**Comment by duyhoangatk** [comment] 2024-06-07 01:58
Hi Prof Yumorishita,
Thank you for your reply, the batch script is now working back normally.
And I continue to learn this software, so I have few more basic questions related to the results:
1. According to the result graph of 「Velocity / Cummulative Displacement」, I think that the areas with blue color are going downward (沈下) due to minus number, areas with red are going upward（隆起）due to plus number. Am I correct ?
2. I found that there are some points that have the cummulative displacement through time different from the time-series graph (check photo as an example). Can you kindly explain why ?
![difference from 2 graphs](https://github.com/yumorishita/LiCSBAS/assets/171003463/283d0ea7-1b86-4e4b-9af0-abdeae633951)
3. When I try to export the time series of the displacement at a specified point text file, I face the 「out of range」error, how can I fix this ?
![error out of range](https://github.com/yumorishita/LiCSBAS/assets/171003463/9deff8a0-b608-42a1-8c4e-7d0e0e61d424)
4. When display the GeoTIFF file that created by LiCSBAS_flt2geotiff.py, is the value of created parameter same as the result graph ? (because for example, I run batch script for a place which has the following range of masked velocity, but when I convert the masked velocity to GeoTIFF and display on QGIS, the value has the range 4.57 ~ -37.207 )
![vel mskd](https://github.com/yumorishita/LiCSBAS/assets/171003463/5c6c22f4-9074-41bf-a86b-802f3aa20c2c)

There are many many new knowledge and terminologies that I still don't know yet, so sorry if I asked these questions.
Waiting for your reply. Thank you

**Comment by yumorishita** [comment] 2024-06-08 12:09
> 1. According to the result graph of 「Velocity / Cummulative Displacement」, I think that the areas with blue color are going downward (沈下) due to minus number, areas with red are going upward（隆起）due to plus number. Am I correct ?

Almost yes, but you should note that LOS displacement includes the EW component as well.

> 2. I found that there are some points that have the cummulative displacement through time different from the time-series graph (check photo as an example). Can you kindly explain why ?

Do you mean that some of the displacement values exceed the max/min color range? It is because the color range is automatically determined by 99% of the data value to ignore outliers. Please try `--auto_crange 100` option.

> 3. When I try to export the time series of the displacement at a specified point text file, I face the 「out of range」error, how can I fix this ?

It is because the location of the point you specified (107/83) is outside of the data (i.e., exceeds the size of the data). Please select the correct point location inside of the data.

> 4. When display the GeoTIFF file that created by LiCSBAS_flt2geotiff.py, is the value of created parameter same as the result graph ? (because for example, I run batch script for a place which has the following range of masked velocity, but when I convert the masked velocity to GeoTIFF and display on QGIS, the value has the range 4.57 ~ -37.207 )

It should be the same. Please check the answer 2 above.

**Comment by duyhoangatk** [comment] 2024-06-10 00:30
Hi Prof Yumorishita,
1. 「Almost yes, but you should note that LOS displacement includes the EW component as well.」
→ Thank you for your information. Actually there is an analysis called 2.5 dimension horizontal analysis (2.5次元水平解析）that can produce EW （東西方向 or 水平方向）displacement and up-down（鉛直方向） displacement results serepately, and I'm doing my job using it.
2. 「Do you mean that some of the displacement values exceed the max/min color range? It is because the color range is automatically determined by 99% of the data value to ignore outliers. Please try --auto_crange 100 option.」
→ Sorry but can you show me how and where to use the --auto_crange 100 option (in Ubuntu LST or in graph directly ? Sorry I'm completely blank)  
3. 「It is because the location of the point you specified (107/83) is outside of the data (i.e., exceeds the size of the data). Please select the correct point location inside of the data.」
→ My mistake here. I just copied the code from your sample pdf file but forgot to change the point coordinate. Thank you for your reply.
4. 「It should be the same. Please check the answer 2 above.」
→ I will try again when Prof can show me how to use the option. But for more details, I wil show the photos.
![different masked velocity values](https://github.com/yumorishita/LiCSBAS/assets/171003463/21bec180-4206-4a94-abab-76d28040898b)

Waiting for your reply. Thank you

**Comment by yumorishita** [comment] 2024-06-10 11:28
`--auto_crange` is the one of the options of `LiCSBAS_plot_ts.py` and `LiCSBAS_disp_img.py`.

> One more thing, for example, I converted the masked vel(1) to GeoTIFF, so the GeoTIFF will be converted in which time ?

What command and arguments did you use to create the GeoTIFF?

**Comment by duyhoangatk** [comment] 2024-06-11 00:09
Hi Prof Yumorishita,
1.「--auto_crange is the one of the options of LiCSBAS_plot_ts.py and LiCSBAS_disp_img.py.」
→ For example, usually I display the results by using 「LiCSBAS_plot_ts.py -i TS_GEOCml1clip/cum_filt.h5 &」code, so if want to use options auto_crange as you recommended, will it be added like: 「LiCSBAS_plot_ts.py  TS_GEOCml1clip/cum_filt.h5 & --auto_crange」? (Sorry if you think I'm asking silly questions)
2. 「What command and arguments did you use to create the GeoTIFF?」
→ Simply copy the code 「LiCSBAS_flt2geotiff.py -i TS_GEOCml1clip/results/vel.mskd -p TS_GEOCml1clip/info/EQA.dem_par」from your sample pdf file to create GeoTIFF (this one is to convert masked velocity graph to GeoTIFF, I think), but still I don't know which time the result is showing...

Waiting for your reply. Thank you

**Comment by yumorishita** [comment] 2024-06-11 11:10
1. Try `LiCSBAS_plot_ts.py TS_GEOCml1clip/cum_filt.h5 --auto_crange 100 &`.
2. Then it is the unfiltered velocity (vel(2)) and have no particular date. vel(1) corresponds to vel.filt.mskd.

**Comment by duyhoangatk** [comment] 2024-06-12 00:06
Hi Prof Yumorishita,
1. 「Try LiCSBAS_plot_ts.py TS_GEOCml1clip/cum_filt.h5 --auto_crange 100 &.」
→ Thank you for your instruction. I will try
2. 「Then it is the unfiltered velocity (vel(2)) and have no particular date. vel(1) corresponds to vel.filt.mskd.」
→ Oh, I didn't notice it. I will try again with vel(1). And if the above code have no particular date, how can I convert it in a particular date ? (I think maybe add the date into the code ? )

Waiting for your reply. Thank you very much

**Comment by yumorishita** [comment] 2024-06-12 11:47
> how can I convert it in a particular date ?

First you should create a float file for a particular date from cum_filt.h5 using LiCSBAS_cum2flt.py.

> 3. I have another problem when running batch file, which is Index error:

I could not reproduce the error using the latest version. Please see https://github.com/yumorishita/LiCSBAS/issues/244#issuecomment-2156004788.

**Comment by duyhoangatk** [comment] 2024-06-13 08:50
Hi Prof Yumorishita,
1. 「First you should create a float file for a particular date from cum_filt.h5 using LiCSBAS_cum2flt.py.」
→ Thank you very much. I will try
2. Actually I'm using the LiCSBAS2. The batch is now running normally again, maybe the error was temporarily occured.

Thank you for your reply. I will contact again if there is any problem.

**Comment by duyhoangatk** [comment] 2024-06-17 01:18
Hi Prof Yumorishita,
About the option --auto_crange 100, the result (take vel(1) as example) with and without the option are different when displaying, but the GeoTIFF's value is taken from the one with the option. So which one is the correct result because this is making me confused. (Please check attached photo)
![image](https://github.com/yumorishita/LiCSBAS/assets/171003463/04202c28-4eef-4f5d-991c-a09580de5de3)
Waiting for your reply. Thank you very much

**Comment by yumorishita** [comment] 2024-06-17 11:24
1. It is just a visualization (color range) difference and both are identical.
2. Yes.
3. You can export a text file using gdal2xyz from GeoTIFF.
4. https://github.com/yumorishita/LiCSBAS/issues/117#issuecomment-878956383

**Comment by duyhoangatk** [comment] 2024-06-17 23:54
Hi Prof Yumorishita,
3. 「You can export a text file using gdal2xyz from GeoTIFF.」
→ Thank you for your infomation, but I don't see any .py file of gdal2xyz in 'bin' folder. Can you please show me how to do it ?
4. I have seen the comment, but what I want to know is the difference of filtered vel(1) and unfiltered velocity vel(2), and how they reflect to the result ? (for example, vel(1) has better noise handling, which reduce noises in result or something like that. Sorry if my question is not clearly pointed)

Waiting for your reply. Thank you very much

**Comment by duyhoangatk** [comment] 2024-06-20 05:15
Hi Prof Yumorishita,
Thank you for your reply. I am now able to use gdal2xyz.
In the sample paper, there is a way to convert the time serires displacement at a specific point ino .txt file. So, is there anyway to convert all points at once because I want to see all but it really takes time to convert every single point for a large area. 
Waiting for your reply. Thank you very much

**Comment by duyhoangatk** [comment] 2024-06-21 01:31
Hi Prof Yumorishita,
I have tried and successfully exported, but it is only in one specific date not whole in time period. Is there anyway to convert in all period time ? (For example I have a result of cummulative displacement of a place from 2015 to 2020, but in according to your solution it can only export all point at only 1 specific date, such as 2019/01/01 not all dates within period)
Waiting for your reply. Thank you

**Comment by yumorishita** [comment] 2024-06-21 12:39
Just iterate exporting by for-loop.
Please attach the full log for the error.

**Comment by duyhoangatk** [comment] 2024-06-23 23:49
Hi Prof Yumorishita,
1.「Just iterate exporting by for-loop.」
→ I think you are meaning to add a for-loop in LiCSBAS_cum2flt.py code, sorry but can you show me how to do it ? (Very sorry for such silly question)
2. 「Please attach the full log for the error.」
→ The server is now under maintenance so I can't reproduce it, maybe it is for fixing the mentioned error. If there is error again, I will show the full log. 

Waiting for your reply. Thank you very much

**Comment by yumorishita** [comment] 2024-06-24 11:08
1. I cannot understand what data format you want to export.

**Comment by duyhoangatk** [comment] 2024-06-25 00:09
HI Prof Yumorishita,
Sorry if my question is difficult to understand. Let me summarize:
I want to export csv file of cummulative displacement of all points in a specific place, in a period of time (ex: 2019~2022). But right now in your code, there is only able to export at one specified coordinate (using LiCSBAS_cum2tstxt.py), not all. 
→ which means basically I have to export each point's cummulative displacement at once, which will take times if I do with large areas.
And then Prof recommend that do the for-loop. I tried to modify the 「LiCSBAS_cum2flt.py」 code and now I can produce all the cum files of cummulative displacement of all points at once, but they are seperated files, not compacted in 1 single cum file. 
→ which means, I still only can convert 1 cum file into csv at once, which will take much times if there are hundreds of cum files.
(Basically, I convert a cummulative displacement cum file into csv file following your instruction: LiCSBAS_cum2flt.py →  LiCSBAS_flt2geotiff.py → gdal2xyz)

So, what I want to ask is: Is there any method to produce all points' cummulative displacement (from LiCSBAS_cum2flt.py step) compacted in only 1 single cum file, which is convenient to convert into csv file ?  
Or is there any method to convert cum files → csv file immediately without converting into GeoTIFF file ?

I hope you can understand with this explanation. 
Waiting for your reply. Thank you very much.

**Comment by yumorishita** [comment] 2024-06-25 11:48
I would iterate LiCSBAS_cum2flt.py → LiCSBAS_flt2geotiff.py → gdal2xyz processing for all dates (by for-loop) and combine the output csv into one. It should not take so long time compared to the LiCSBAS processing time even if the number of epochs is more than a hundred.

Regarding the error, please attach the full log.

**Comment by duyhoangatk** [comment] 2024-06-25 23:27
Hi Prof Yumorishita,
1. 「I would iterate LiCSBAS_cum2flt.py → LiCSBAS_flt2geotiff.py → gdal2xyz processing for all dates (by for-loop) and combine the output csv into one. It should not take so long time compared to the LiCSBAS processing time even if the number of epochs is more than a hundred.」
→ Thank you for your reply. I will try 
2. 「Regarding the error, please attach the full log.」→ You mean this:
Start step: 01
End step:   16
Log file:   log/202406260823batch_LiCSBAS_01_16.log


LiCSBAS01_get_geotiff.py ver1.6.4 20230215 Y. Morishita
LiCSBAS01_get_geotiff.py -s 20190101

Frame ID is 055A_06858_131510

055A_06858_131510.geo.E.tif already exist. Skip download.
055A_06858_131510.geo.N.tif already exist. Skip download.
055A_06858_131510.geo.U.tif already exist. Skip download.
055A_06858_131510.geo.hgt.tif already exist. Skip download.

Download baselines
    baselines, 6.54KB, 1s, 6.54KB/s
Download network.png
    network.png, 206.41KB, 2s, 103.21KB/s
Download metadata.txt
    metadata.txt, 249.0B, 1s, 249.0B/s

Searching latest epoch for mli...
  120/129
No mli available on https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/55/055A_06858_131510/epochs/



Download geotiff of unw and cc
Traceback (most recent call last):
  File "/home/atk/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 500, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/atk/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 340, in main
    print('{} IFGs available from {} to {}'.format(n_ifg, imdates[0], imdates[-1]), flush=True)
                                                          ~~~~~~~^^^
IndexError: list index out of range

Please check. Waiting for your reply. Thank you very much.

**Comment by yumorishita** [comment] 2024-06-27 11:43
You are using the old version: `LiCSBAS01_get_geotiff.py ver1.6.4 20230215 Y. Morishita`
The latest version is v1.6.5.
https://github.com/yumorishita/LiCSBAS2/blob/f1e2592dfb37cfde243f644fcfe554ab4b67bba7/bin/LiCSBAS01_get_geotiff.py#L99

**Comment by duyhoangatk** [comment] 2024-06-30 23:58
Hi Prof Yumorishita,
Thank you for your reply. I will try again with newest version.

**Comment by yumorishita** [comment] 2024-07-01 11:29
The error should not depend on the AOI. Please attached the full log again.

**Comment by duyhoangatk** [comment] 2024-07-02 00:25
Hi Prof Yumorishita,
I have tried again, and the error log is the same as above comment:

(licsbas) atk@atkttwc0725:/mnt/c/licsbas/Halong/055A_06858_131510$ ./batch_LiCSBAS.sh

Start step: 01
End step:   16
Log file:   log/202407020918batch_LiCSBAS_01_16.log


LiCSBAS01_get_geotiff.py ver1.6.5 20240607 Y. Morishita
LiCSBAS01_get_geotiff.py -s 20210101

Frame ID is 055A_06858_131510

Download 055A_06858_131510.geo.E.tif
    055A_06858_131510.geo.E.tif, 13.09MB, 16s, 837.87KB/s
Download 055A_06858_131510.geo.N.tif
    055A_06858_131510.geo.N.tif, 13.31MB, 14s, 973.87KB/s
Download 055A_06858_131510.geo.U.tif
    055A_06858_131510.geo.U.tif, 13.09MB, 10s, 1.31MB/s
Download 055A_06858_131510.geo.hgt.tif
    055A_06858_131510.geo.hgt.tif, 13.09MB, 26s, 515.61KB/s

Download baselines
    baselines, 6.54KB, 1s, 6.54KB/s
Download network.png
    network.png, 206.41KB, 2s, 103.21KB/s
Download metadata.txt
    metadata.txt, 249.0B, 1s, 249.0B/s

Searching latest epoch for mli...
   60/ 67
No mli available on https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/55/055A_06858_131510/epochs/



Download geotiff of unw and cc
Traceback (most recent call last):
  File "/home/atk/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 502, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/atk/LiCSBAS2/bin/LiCSBAS01_get_geotiff.py", line 342, in main
    print('{} IFGs available from {} to {}'.format(n_ifg, imdates[0], imdates[-1]), flush=True)
                                                          ~~~~~~~^^^
IndexError: list index out of range

I used the frame ID: 055A_06858_131510, do05op_clip="y", p05_clip_range_geo="107.03/107.05/20.96/20.98"
Date is not very inportant.
Am I doing something wrong with these parameters ? 

Waiting for your reply. Thank you very much.

**Comment by duyhoangatk** [comment] 2024-07-03 00:01
Hi Prof Yumorishita,
Thank you for your reply. I will change the date and try again

**Comment by duyhoangatk** [comment] 2024-08-27 00:03
Hi Prof. Yumorishita,
Is the COMET site now in maintenance ? I tried to run the batch script but then failed at the 1st data downloading step from ysterday.
Sorry for asking question not related to the LiCSBAS but still hope for your reply. Thank you

**Comment by yumorishita** [comment] 2024-08-27 14:50
I think so.
https://x.com/COMET_database/status/1826570211601838537

**Closed** 2024-12-10 11:57 UTC
