### ISSUE TITLE
Wrong result in LiCSBAS_plot_ts.py and LiCSBAS_flt2geotiff.py

### ISSUE THREAD

**Issue by lamebird** [yumorishita/LiCSBAS#42] opened 2020-11-21 18:57 UTC
Hi!
So I just updated to LiCSBAS v1.3.19 and try to process some scene
And I got wrong result when trying to plot with LiCSBAS_plot_ts.py as I just got 3 pixels on it:
![image](https://user-images.githubusercontent.com/19585925/99885082-10328f00-2c65-11eb-80ba-6bb61ad57951.png)
The result of exporting vel.filt by LiCSBAS_flt2geotiff.py is same:
![image](https://user-images.githubusercontent.com/19585925/99885039-c8ac0300-2c64-11eb-8716-b6faeb3d3669.png)
Even though all of the result png doesn't seem wrong:
![vel filt](https://user-images.githubusercontent.com/19585925/99885064-ef6a3980-2c64-11eb-8151-de756d5330c7.png)
![coh_avg](https://user-images.githubusercontent.com/19585925/99885100-22143200-2c65-11eb-9d6a-5950a5b31cf6.png)

But, when I open past processed scene it shows normal result:
![image](https://user-images.githubusercontent.com/19585925/99885197-d0b87280-2c65-11eb-8cb8-b513db7a9366.png)

So I think the problem is in the processing algorithm?

**Comment by yumorishita** [comment] 2020-11-21 23:14
Can you upload the full log file and batch script to reproduce the error?

**Comment by yumorishita** [comment] 2020-11-22 01:11
I think the sparse result is because most of the pixels were masked in step15. Please try tweaking parameters and rerun from step15.

The remaining ifgs (i.e., network) seem to be different between the past and new result. I wonder if you changed parameters in steps 11-12 or added new ifgs that might have weird phases.

**Comment by yumorishita** [comment] 2020-11-30 06:06
Has the problem been solved?

**Comment by alejobeap** [comment] 2020-11-30 17:13
Dear 
I'm trying to get a time series with the images used for the processing, is it possible to do it ?

Thanks
Alejandro

**Comment by yumorishita** [comment] 2020-11-30 23:30
Sorry, I don't understand what you want to do. The time series shown by LiCSBAS_plot_ts.py is derived from the processed images. What do you mean?

**Comment by alejobeap** [comment] 2020-12-01 12:27
I'm trying to plot the all images that  were used for the velocity map or cumulative displacement. the time series that is obtained with LiCSBAS_plot_ts.py. It is possible to plot all the images by dates that were used?

Thanks

**Comment by yumorishita** [comment] 2020-12-01 12:42
You can show the cumulative displacement map at all used image dates by sliding the bottom slide bar in the image viewer.

**Comment by alejobeap** [comment] 2020-12-01 12:45
Thanks. 
Yes I did, but is there any way to extract those images as geotiff or png?

Thank you very much for your help

**Comment by yumorishita** [comment] 2020-12-01 13:47
[LiCSBAS_cum2flt.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_cum2fltpy) and [LiCSBAS_flt2geotiff.py](https://github.com/yumorishita/LiCSBAS/wiki/4_other_tools#licsbas_flt2geotiffpy) can do it.

**Comment by alejobeap** [comment] 2020-12-01 13:53
Thanks

**Comment by lamebird** [comment] 2020-12-02 03:35
> I think the sparse result is because most of the pixels were masked in step15. Please try tweaking parameters and rerun from step15.
> 
> The remaining ifgs (i.e., network) seem to be different between the past and new result. I wonder if you changed parameters in steps 11-12 or added new ifgs that might have weird phases.


Ah! I'm sorry for not realizing that pixels that did not appear were masked.
And I don't change any parameters in 11 - 15.
I wonder why most of the ifg were removed:
![network13](https://user-images.githubusercontent.com/19585925/100825022-c11d0300-3489-11eb-94a7-91846700af70.png)
Any tips what should i do with this particular case and what might be the cause?

**Comment by yumorishita** [comment] 2020-12-02 04:00
Can you upload the full log files of the past and new processing? I need more detailed information to investigate the cause.

**Comment by yumorishita** [comment] 2020-12-22 23:39
It seems that there is no more question. I close this issue.

**Closed by yumorishita** 2020-12-22 23:39 UTC
