### ISSUE TITLE
Error in LiCSBAS12_loop_closure.py ( A colormap named "SCM.romaO" is already registered.)

### ISSUE THREAD

**Issue by yogen1992** [yumorishita/LiCSBAS#236] opened 2023-03-30 05:59 UTC
I have been processing LiCSAR data from Indonesia, Pakistan, and India. However, I got a problem in step 12 with loop closure in some frames. I have tried various loop closure thresholds (from 0.5 to 3.5), but the error remains the same. For reference, I have uploaded the log file.
[202303291411batch_LiCSBAS_01_16.log](https://github.com/yumorishita/LiCSBAS/files/11108257/202303291411batch_LiCSBAS_01_16.log)

**Comment by Zuzchan** [comment] 2023-03-30 06:27
The error occurred in step 12 and is caused by the version of matplotlib (see https://github.com/yumorishita/LiCSBAS/issues/176#issuecomment-1303124941). Please downgrade matplotlib. also, it is recommended to use python3.8.

**Comment by yogen1992** [comment] 2023-03-30 07:08
Thanks, it works. Cheers

**Comment by Zuzchan** [comment] 2023-03-30 09:41
Can you please show how you wrote the code to downgrade it? My friend has an issue with it.

**Comment by Zuzchan** [comment] 2023-03-30 09:50
Yeah, they tried this, butt got this error
![WhatsApp Image 2023-03-30 at 12 21 31](https://user-images.githubusercontent.com/120248666/228798573-e9f19853-35d4-419f-9506-972cc6c87a30.jpeg)

**Comment by yogen1992** [comment] 2023-03-30 09:59
Haha, I am not sure then. I am using WSL, where this command has worked.

However, you can try to uninstall the current Matplotlib version by 
"pip3 uninstall matplotlib"
And then re-install by using
pip3 install matplotlib==3.1.0 --force-reinstall

**Comment by Zuzchan** [comment] 2023-04-07 15:11
Well 
Imma update 
I solved using two ways 
I don't know of one or both of them helped,  I'll write in case someone would face the same error 
I installed python 3.8 then made an environment for it and set it as default followed this video
https://linuxize.com/post/how-to-install-python-3-8-on-ubuntu-18-04/#:~:text=Installing%20Python%203.8%20on%20Ubuntu%201%20Update%20the,extract%20the%20gzipped%20archive%3Atar%20-xf%20Python-3.8.0.tgz%20See%20More

Second,  I installed gdal then it worked 
conda install gdal


Thank you for your reply, you can close the issue if you don't have more questions to prof. Yumorishita.

**Comment by HamedAmirkhani1378** [comment] 2023-05-03 20:26
> Well Imma update I solved it using two ways I don't know if one or both of them helped, I'll write in case someone would face the same error I installed python 3.8 then made an environment for it and set it as default followed this video https://linuxize.com/post/how-to-install-python-3-8-on-ubuntu-18-04/#:~:text=Installing%20Python%203.8%20on%20Ubuntu%201%20Update%20the,extract%20the%20gzipped%20archive%3Atar%20-xf%20Python-3.8.0.tgz%20See%20More
> 
> Second, I installed gdal then it worked conda install gdal
> 
> Thank you for your reply, you can close the issue if you don't have more questions to prof. Yumorishita.

Hi Zuzchan
I created the virtual environment according to the link you shared. How can I install and run LiCSBAS via virtual env?

**Closed** 2023-05-24 13:24 UTC
